Need help
Getting an error: "               File "mergerMatcher.py", line 84, in <module>                 "
                                              for each_pair in dictionary.get(row[0]):
                                               TypeError: 'NoneType' object is not iterable

Idk why because dictionary.get() should return the value (the list) for the corresponding class title so it SHOULD be iterable
help